services:
  gophermart:
    build:
      context: .
      dockerfile: docker/gophermart/Dockerfile
    depends_on:
      postgres:
        condition: service_started
    environment:
      DATABASE_URI: postgresql://postgres:123456@postgres/gophermart
    ports:
      - "8081:8081"
    entrypoint: "go run ./cmd/gophermart"

  accrual:
    build:
      context: .
      dockerfile: docker/accrual/Dockerfile
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "gophermart"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: