// Code generated by MockGen. DO NOT EDIT.
// Source: accrualRepository.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"

	models "github.com/dcwk/gophermart/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAccrualRepository is a mock of AccrualRepository interface.
type MockAccrualRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualRepositoryMockRecorder
}

// MockAccrualRepositoryMockRecorder is the mock recorder for MockAccrualRepository.
type MockAccrualRepositoryMockRecorder struct {
	mock *MockAccrualRepository
}

// NewMockAccrualRepository creates a new mock instance.
func NewMockAccrualRepository(ctrl *gomock.Controller) *MockAccrualRepository {
	mock := &MockAccrualRepository{ctrl: ctrl}
	mock.recorder = &MockAccrualRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualRepository) EXPECT() *MockAccrualRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccrualRepository) Create(ctx context.Context, accrual *models.Accrual) (*models.Accrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, accrual)
	ret0, _ := ret[0].(*models.Accrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccrualRepositoryMockRecorder) Create(ctx, accrual interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccrualRepository)(nil).Create), ctx, accrual)
}

// Update mocks base method.
func (m *MockAccrualRepository) Update(ctx context.Context, accrual *models.Accrual) (*models.Accrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, accrual)
	ret0, _ := ret[0].(*models.Accrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccrualRepositoryMockRecorder) Update(ctx, accrual interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccrualRepository)(nil).Update), ctx, accrual)
}
