services:
  gophermart:
    build:
      context: ..
      dockerfile: ./docker/gophermart/Dockerfile
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ../config.yaml:/app/config.yaml

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "gophermart"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  gophermart-migrations:
    build:
      context: ..
      dockerfile: ./docker/gophermart/Dockerfile
    depends_on:
      gophermart:
        condition: service_started
    volumes:
      - ../config.yaml:/app/config.yaml

volumes:
  postgres: